version: "3.8"

services:
  api:
    ports:
      - 9229:9229
    volumes:
      - ../api/src:/app/src
      #- ../api/node_modules:/app/node_modules
    command: ["npm", "run", "debug"]

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo-network
    depends_on:
      mongodb:
        condition: service_healthy
