version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0.0-rc16-noble
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    container_name: api
    build:
      context: ../api
    env_file: .env
    ports:
      - ${API_PORT}:3000
    networks:
      - mongo-network
    depends_on:
      mongodb:
        condition: service_healthy

    healthcheck:
      test: "curl -f http://localhost:3000 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  mongo-network:

volumes:
  mongo-data:
